create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_red_ml integer null,
    gold integer null,
    num_blue_ml integer null,
    num_green_ml integer null default 0,
    num_dark_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;


create table
  public.potion_inv (
    id bigint generated by default as identity,
    inventory integer null,
    potion_type integer[] null,
    sku text null,
    cost integer null,
    constraint potion_inv_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer text null,
    payment text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id bigint not null,
    quantity integer null,
    potion_id bigint null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_inv (id)
  ) tablespace pg_default;